#!/usr/bin/env python3
import matplotlib
matplotlib.use("TkAgg")
# -*- coding: utf-8 -*-
"""corona2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1adv-YTZYRVZRRu6RKyZp0XspJQNDDaOw
"""

import pandas as pd
import datetime
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

url = 'https://github.com/nytimes/covid-19-data/raw/master/us-states.csv'

data = pd.read_csv(url)
data = data[data['state'] == 'Massachusetts']
data

dates = data['date']
x = pd.to_datetime(dates)
y = data['cases']

DF = pd.DataFrame()
DF['cases'] = y
DF = DF.set_index(x)

fig, ax = plt.subplots()
fig.subplots_adjust(bottom=0.1)


plt.xticks(rotation=90)
plt.figure(figsize=(25,10))
plt.plot(DF)
plt.show()
#plt.plot(x,y)
#fig = plt.figure(figsize=(20,10))
#ax = fig.add_subplot(111)
#plt.scatter(x, y)









